

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <div className="bg-teal-500">
      {children}
    </div>
  )
}
