import { Inter } from 'next/font/google'
import './globals.css'

import NavBar from './components/nav/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
        {children}
        </main>
      </body>
    </html>
  )
}
